### ISSUE TITLE
Integrar no Covenant

### ISSUE THREAD

**Issue by FFY00** [mrpiracyPT/repository.mrpiracy#2]
Olá, eu gostaria de usar o vosso código para adicionar o mrpiracy como uma source no Covenant. Gostaria de saber se vocês têm algum problema com isto e se poderia prosseguir com o port?

Obrigado,
Filipe

**Comment by mrpiracyPT** [comment]
Olá, pedimos por favor que não o faça.

Cumprimentos, obrigado

**Comment by FFY00** [comment]
Ok, obrigado na mesma.
