### ISSUE TITLE
Can't open the addon in Kodi

### ISSUE THREAD

**Issue by rdscorreia74** [mrpiracyPT/repository.mrpiracy#3]
@mrpiracyPT 
Já há alguns dias (talvez semanas) que o vosso addon me dá erro e não consigo sequer chegar ao menu onde se escolhe filmes/séries/etc.
Sabes dizer o que se passa? Vejo que o último commit tem cerca de 2 meses...

Translation to English
It's been several days (maybe weeks) that this addon has been giving me errors and I can't even reach the addon's menu where you get to choose between movies/tvshows/etc.
Do you know what's wrong? I see that the last code commit has already been 2 months ago...

**Comment by mrpiracyPT** [comment]
Boas
Experimente usar dns, poderá ser algum bloqueio da sua operadora

Obrigado

**Comment by rdscorreia74** [comment]
Boas.
Pode-se escrever tudo em Português no github? Tinha a sensação que eles apagavam se não estivesse em Inglês.
Eu uso os DNS's do OpenDNS no meu router...
Por isso não estou a ver. Há algum domínio que eu deva experimentar no dispositivo para ver se chega ao destino? Por exemplo, pingar:
- mrpiracy.ml
- mrpiracy.gq
- mrpiracy.xyz

outros?
Eu do meu PC chego lá a estes todos e do meu RPi que uso com o Kodi também.
Há mais algum que deva experimentar?
Cumps

**Comment by mrpiracyPT** [comment]
Boas, por acaso não sei se apagam.
Supostamente se esses dão então devia funcionar bem.
Tem a versão 0.8.7?
Veja o ficheiro log do kodi ou envie para percebermos o erro, obrigado

**Comment by rdscorreia74** [comment]
Olá @mrpiracyPT.
Fiz reset aos settings do addon, removi o addon, reinstalei o addon, reconfigurei o addon e ficou tudo a funcionar bem.
Não sei o que terá sido mas já passou.
Obrigado pela ajuda.
Cumprimentos.
